### ISSUE TITLE
login ko

### ISSUE THREAD

**Issue by rems2rems** [huiledecode/OTF-#1]
salut stephane

(je suis remy de l'exia pau)

j'ai installé sans probleme otf chez moi en suivant le tuto de la page d'accueil.

par contre sur la page d'accueil, lorsque je me loggue avec admin/otf, j'ai droit à:

Connection Failed
Passport account not found in db for login : admin

dans les logs rien de particulier je crois...

une idée?
++

**Comment by Stephanux** [comment]
Salut Remy,

Tu as fait le mongorestore ./otf_demo depuis le dossier dump ?

D'après le message ça ressemble à un truc comme ça ,;-)

Adichatz ;-)
Steph.

**Comment by Stephanux** [comment]
Re,

Je te conseille d'installer Mongo Management Studio pour avoir un accès
pratique à la base otf_demo.

http://www.litixsoft.de/english/mms/

Copier le dossier "lx-mms" dans /opt et lancer le "./start" il affiche
l'url de connexion.

Steph.

**Comment by CorentinDy** [comment]
Souvent c'est bien le mongorestore et le fait que mongo démarre mal en `--replSet`

**Comment by epa64** [comment]
Salut à tous

Normalement le repset est nécessaire pour le module conf/otf_opolog.
Normalement ds les log level INFO on peut voir si la connexion à mongo est ok.
Sinon même à chaud on peut modier le level du log à debug ds conf/otf_config.json.
Le message d'erreur est clair il n existe pas de login admin ds mongo.
Comme l a dit Stef c est plutôt un pb de données ds mongo.
@+
Eric

<div>-------- Message d'origine --------</div><div>De : Corentin Dehay notifications@github.com </div><div>Date :14/05/2015  16:54  (GMT+01:00) </div><div>A : huiledecode/OTF- OTF-@noreply.github.com </div><div>Objet : Re: [OTF-] login ko (#1) </div><div>
</div>Souvent c'est bien le mongorestore et le fait que mongo démarre mal en --replSet
